name: Linting
on: [pull_request]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1.1.0
  Security:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ github.token }}
